# This file has moved.
# Databricks notebook version -> notebooks/databricks_tools_oauth_validation.py
# Standalone Python script    -> scripts/validate_tools_oauth.py

# Databricks notebook source
# DBTITLE 1,Overview
# MAGIC %md
# MAGIC # Databricks Tools OAuth Validation
# MAGIC
# MAGIC This notebook validates the OAuth configuration needed for **Databricks Tools in Glean** (Genie and SQL actions in Assistant and Agents).
# MAGIC
# MAGIC ## Before you run this
# MAGIC
# MAGIC | What | Where to find it |
# MAGIC |---|---|
# MAGIC | Workspace Host URL | Your Databricks workspace browser bar, e.g. `https://dbc-xxxx.cloud.databricks.com` |
# MAGIC | Client ID | Databricks Account Console → Settings → App Connections |
# MAGIC | Client Secret | Copied at time of App Connection creation (not retrievable after) |
# MAGIC | SQL Warehouse ID | *(optional)* — auto-discovered if left blank |
# MAGIC | Genie Space ID | *(optional)* — only needed to test the Genie API |
# MAGIC
# MAGIC ## What this notebook tests
# MAGIC
# MAGIC 1. **OIDC Discovery** — confirms workspace OIDC endpoints are reachable and returns URLs to use in Glean
# MAGIC 2. **M2M Client Credentials test** — confirms the App Connection exists and the secret is correct
# MAGIC 3. **SQL Statement API test** *(optional)* — runs a query against `samples.tpch.orders`
# MAGIC 4. **Genie API test** *(optional)* — starts a Genie conversation to confirm the action will work
# MAGIC
# MAGIC > **Important:** Steps 1–2 use M2M (client_credentials). A PASS is a strong signal but the full
# MAGIC > Glean tools flow uses U2M (user OAuth with browser redirect). Also verify the redirect URL in
# MAGIC > your Databricks App Connection exactly matches the callback URL generated by Glean.
# MAGIC
# MAGIC ### Recommended test dataset
# MAGIC The `samples.tpch` catalog is available in **every** Databricks workspace with no setup required.
# MAGIC
# MAGIC ---
# MAGIC *Questions? Ping sabrina.wang@glean.com*

# COMMAND ----------

# DBTITLE 1,Widget Inputs
dbutils.widgets.text("WORKSPACE_HOST", "", "Workspace Host")
dbutils.widgets.text("CLIENT_ID", "", "Client ID")
dbutils.widgets.text("CLIENT_SECRET", "", "Client Secret")
dbutils.widgets.text("ACCOUNT_ID", "", "Account ID (optional)")
dbutils.widgets.text("GENIE_SPACE_ID", "", "Genie Space ID (optional)")
dbutils.widgets.text("WAREHOUSE_ID", "", "SQL Warehouse ID (optional)")

WORKSPACE_HOST = dbutils.widgets.get("WORKSPACE_HOST").rstrip("/")
CLIENT_ID      = dbutils.widgets.get("CLIENT_ID").strip()
CLIENT_SECRET  = dbutils.widgets.get("CLIENT_SECRET").strip()
ACCOUNT_ID     = dbutils.widgets.get("ACCOUNT_ID").strip()
GENIE_SPACE_ID = dbutils.widgets.get("GENIE_SPACE_ID").strip()
WAREHOUSE_ID   = dbutils.widgets.get("WAREHOUSE_ID").strip()

print("Configuration loaded:")
print(f"  Workspace Host : {WORKSPACE_HOST}")
print(f"  Account ID     : {ACCOUNT_ID or '(not set)'}")
print(f"  Client ID      : {CLIENT_ID or '(not set)'}")
print(f"  Client Secret  : {'*' * len(CLIENT_SECRET) if CLIENT_SECRET else '(not set)'}")
print(f"  Genie Space ID : {GENIE_SPACE_ID or '(not set)'}")
print(f"  Warehouse ID   : {WAREHOUSE_ID or '(not set)'}")

# COMMAND ----------

# DBTITLE 1,Step 2 - OIDC Discovery
# MAGIC %md
# MAGIC ## Step 2 — OIDC Discovery
# MAGIC
# MAGIC Hits the OIDC discovery endpoint and returns the full OAuth server configuration.
# MAGIC
# MAGIC What to look for:
# MAGIC - `authorization_endpoint` — **Authorization URL** to enter in Glean's tool config
# MAGIC - `token_endpoint` — **Token URL** to enter in Glean's tool config
# MAGIC - `scopes_supported` — confirm `all-apis` and `offline_access` are both listed

# COMMAND ----------

import requests
import json

OIDC_DISCOVERY_URL = f"{WORKSPACE_HOST}/oidc/.well-known/oauth-authorization-server"

try:
    resp = requests.get(OIDC_DISCOVERY_URL, timeout=10)
    resp.raise_for_status()
    oidc_config = resp.json()
    print(f"[PASS] OIDC discovery endpoint reachable")
    print(f"  URL    : {OIDC_DISCOVERY_URL}")
    print(f"  Status : {resp.status_code}")
    print()
    print(f"  authorization_endpoint : {oidc_config.get('authorization_endpoint')}")
    print(f"  token_endpoint         : {oidc_config.get('token_endpoint')}")
    print()
    scopes = oidc_config.get('scopes_supported', [])
    for required_scope in ['all-apis', 'offline_access']:
        status = 'found' if required_scope in scopes else 'MISSING'
        print(f"  scope '{required_scope}': {status}")
except Exception as e:
    oidc_config = {}
    print(f"[FAIL] Could not reach OIDC discovery endpoint")
    print(f"  URL   : {OIDC_DISCOVERY_URL}")
    print(f"  Error : {e}")
    print("  Check that WORKSPACE_HOST is correct and reachable.")

# COMMAND ----------

# DBTITLE 1,Step 3 - M2M Token Test
# MAGIC %md
# MAGIC ## Step 3 — M2M Client Credentials Test
# MAGIC
# MAGIC **PASS means:** The App Connection exists and the Client Secret is correct.
# MAGIC
# MAGIC **PASS does NOT prove:** Full U2M flow will work. Also verify:
# MAGIC - Exact Glean callback URL is set as redirect URL in the App Connection
# MAGIC - `offline_access` scope is enabled
# MAGIC
# MAGIC **Common failures:**
# MAGIC - `invalid_client` — wrong Client ID or Secret
# MAGIC - `OAuth application ... not available in Databricks account` — Client ID is a service principal secret, not an App Connection. Go to Account Console → Settings → App Connections and create one.

# COMMAND ----------

TOKEN_URL = f"{WORKSPACE_HOST}/oidc/v1/token"

if not CLIENT_ID or not CLIENT_SECRET:
    print("[SKIP] CLIENT_ID or CLIENT_SECRET is empty. Fill in the widgets and re-run from Cell 2.")
else:
    try:
        token_resp = requests.post(
            TOKEN_URL,
            data={"grant_type": "client_credentials", "scope": "all-apis"},
            auth=(CLIENT_ID, CLIENT_SECRET),
            timeout=10,
        )
        if token_resp.status_code == 200:
            token_data = token_resp.json()
            print("[PASS] Client credentials are valid.")
            print(f"  Token type : {token_data.get('token_type')}")
            print(f"  Expires in : {token_data.get('expires_in')} seconds")
            print(f"  Scope      : {token_data.get('scope')}")
        else:
            print(f"[FAIL] HTTP {token_resp.status_code}")
            try:
                err = token_resp.json()
                print(f"  error             : {err.get('error')}")
                print(f"  error_description : {err.get('error_description')}")
            except Exception:
                print(f"  Raw response: {token_resp.text}")
    except Exception as e:
        token_resp = None
        print(f"[FAIL] Request error: {e}")

# COMMAND ----------

# DBTITLE 1,Step 4 - Summary
# MAGIC %md
# MAGIC ## Step 4 — Summary and Glean Configuration Values
# MAGIC
# MAGIC Prints a summary of all checks and the exact values to copy into Glean's Databricks tools config.

# COMMAND ----------

oidc_ok  = bool(oidc_config.get("authorization_endpoint"))
creds_ok = 'token_resp' in dir() and token_resp is not None and token_resp.status_code == 200

SEP = "=" * 65
print(SEP)
print("Databricks Tools OAuth Validation Summary")
print(SEP)

print(f"\nWorkspace Host : {WORKSPACE_HOST}")
print(f"Account ID     : {ACCOUNT_ID or '(not set)'}")
print(f"Client ID      : {CLIENT_ID or '(not set)'}")
if GENIE_SPACE_ID:
    print(f"Genie Space ID : {GENIE_SPACE_ID}")
if WAREHOUSE_ID:
    print(f"Warehouse ID   : {WAREHOUSE_ID}")

print(f"\nCheck 1 - OIDC Discovery     : {'PASS' if oidc_ok else 'FAIL'}")
if oidc_ok:
    print(f"  authorization_endpoint : {oidc_config.get('authorization_endpoint')}")
    print(f"  token_endpoint         : {oidc_config.get('token_endpoint')}")
else:
    print("  Fix: verify WORKSPACE_HOST is correct and reachable.")

print(f"\nCheck 2 - M2M Token Test     : {'PASS' if creds_ok else 'FAIL'}")
if not creds_ok and CLIENT_ID and CLIENT_SECRET:
    try:
        err = token_resp.json()
        print(f"  {err.get('error')}: {err.get('error_description')}")
        if "not available in Databricks account" in (err.get('error_description') or ''):
            print("  Fix: this Client ID is not an App Connection.")
            print("       Go to Account Console > Settings > App Connections and create a new connection.")
    except Exception:
        pass

print()
print(SEP)
print("Glean Tools Configuration")
print(SEP)
print(f"  Host URL           : {WORKSPACE_HOST}")
print(f"  Authorization URL  : {oidc_config.get('authorization_endpoint', WORKSPACE_HOST + '/oidc/v1/authorize')}")
print(f"  Token URL          : {oidc_config.get('token_endpoint', WORKSPACE_HOST + '/oidc/v1/token')}")
print(f"  Scopes             : all-apis,offline_access")
if GENIE_SPACE_ID:
    print(f"  Genie Space ID     : {GENIE_SPACE_ID}")
if WAREHOUSE_ID:
    print(f"  Warehouse ID       : {WAREHOUSE_ID}")
print()
print("After saving the Glean tool, copy the generated callback URL")
print("back into the Databricks App Connection redirect URLs field.")
print(SEP)
print()
print("Questions? Ping sabrina.wang@glean.com")

# COMMAND ----------

# DBTITLE 1,Step 5 (Optional) - SQL Smoke Test
# MAGIC %md
# MAGIC ## Step 5 (Optional) — SQL Statement API Smoke Test
# MAGIC
# MAGIC Verifies the token works for data access by running a query against `samples.tpch.orders`.
# MAGIC Available in **every** Databricks workspace with no setup required.
# MAGIC
# MAGIC - Auto-discovers a running warehouse if `WAREHOUSE_ID` is blank
# MAGIC - This is the closest programmatic proxy for what Glean's SQL tool will do via U2M

# COMMAND ----------

import time

if not creds_ok:
    print("[SKIP] Token test failed in Step 3 — cannot run smoke test.")
else:
    access_token = token_data["access_token"]
    headers = {"Authorization": f"Bearer {access_token}"}

    warehouse_id = WAREHOUSE_ID
    if not warehouse_id:
        print("No WAREHOUSE_ID provided — discovering available warehouses...\n")
        wh_resp = requests.get(f"{WORKSPACE_HOST}/api/2.0/sql/warehouses", headers=headers, timeout=10)
        if wh_resp.status_code == 200:
            warehouses = wh_resp.json().get("warehouses", [])
            if warehouses:
                running = [w for w in warehouses if w.get("state") == "RUNNING"]
                chosen = running[0] if running else warehouses[0]
                warehouse_id = chosen["id"]
                print(f"Found {len(warehouses)} warehouse(s). Using: {chosen['name']} (ID: {warehouse_id}, State: {chosen.get('state')})")
            else:
                print("[SKIP] No SQL warehouses found. Create one at SQL > SQL Warehouses > Create.")
                warehouse_id = None
        else:
            print(f"[FAIL] Could not list warehouses: HTTP {wh_resp.status_code}")
            warehouse_id = None
    else:
        print(f"Using provided WAREHOUSE_ID: {warehouse_id}")

# COMMAND ----------

SQL_TEST_QUERY = """
SELECT
  o_orderstatus AS status,
  COUNT(*) AS order_count,
  ROUND(SUM(o_totalprice), 2) AS total_value
FROM samples.tpch.orders
GROUP BY o_orderstatus
ORDER BY total_value DESC
LIMIT 5
"""

if not creds_ok:
    print("[SKIP] No valid token.")
elif not warehouse_id:
    print("[SKIP] No warehouse available.")
else:
    print(f"Executing query against samples.tpch.orders...\n")
    stmt_resp = requests.post(
        f"{WORKSPACE_HOST}/api/2.0/sql/statements",
        headers=headers,
        json={"warehouse_id": warehouse_id, "statement": SQL_TEST_QUERY, "wait_timeout": "30s", "disposition": "INLINE"},
        timeout=60,
    )
    if stmt_resp.status_code == 200:
        result = stmt_resp.json()
        state = result.get("status", {}).get("state")
        if state == "SUCCEEDED":
            print("[PASS] SQL Statement API test succeeded!\n")
            columns = [c["name"] for c in result.get("manifest", {}).get("schema", {}).get("columns", [])]
            rows = result.get("result", {}).get("data_array", [])
            print(f"  {'  |  '.join(columns)}")
            for row in rows:
                print(f"  {'  |  '.join(str(v) for v in row)}")
        else:
            print(f"[FAIL] Statement state: {state}")
            print(f"  {result.get('status', {}).get('error', {}).get('message', 'unknown error')}")
    else:
        print(f"[FAIL] HTTP {stmt_resp.status_code}: {stmt_resp.text[:300]}")

# COMMAND ----------

# DBTITLE 1,Step 6 (Optional) - Genie API Test
# MAGIC %md
# MAGIC ## Step 6 (Optional) — Genie API Test
# MAGIC
# MAGIC Tests the Genie API directly if you provide a `GENIE_SPACE_ID`.
# MAGIC
# MAGIC **To create a test Genie space using samples data:**
# MAGIC 1. Go to Workspace > + New > Genie space
# MAGIC 2. Add tables: `samples.tpch.orders`, `samples.tpch.customer`, `samples.tpch.nation`
# MAGIC 3. Copy the space ID from the URL and paste it into the `GENIE_SPACE_ID` widget

# COMMAND ----------

GENIE_TEST_QUESTION = "How many total orders are there?"

if not GENIE_SPACE_ID:
    print("[SKIP] No GENIE_SPACE_ID provided.")
    print("  To test: create a Genie space, add samples.tpch tables, paste the space ID in the widget above.")
elif not creds_ok:
    print("[SKIP] No valid token.")
else:
    print(f"Testing Genie API with space: {GENIE_SPACE_ID}")
    print(f"Question: {GENIE_TEST_QUESTION}\n")
    genie_resp = requests.post(
        f"{WORKSPACE_HOST}/api/2.0/genie/spaces/{GENIE_SPACE_ID}/start-conversation",
        headers=headers,
        json={"content": GENIE_TEST_QUESTION},
        timeout=30,
    )
    if genie_resp.status_code == 200:
        genie_data = genie_resp.json()
        print("[PASS] Genie API responded successfully!")
        print(f"  Conversation ID : {genie_data.get('conversation_id')}")
        print(f"  Message ID      : {genie_data.get('message_id')}")
        print("  The Genie space is reachable and accepting questions.")
    elif genie_resp.status_code == 404:
        print(f"[FAIL] Genie space not found: {GENIE_SPACE_ID}")
        print("  Verify the space ID and that the credentials have access.")
    elif genie_resp.status_code == 403:
        print(f"[FAIL] Permission denied. Grant CAN_USE access to the App Connection service principal on the Genie space.")
    else:
        print(f"[FAIL] HTTP {genie_resp.status_code}: {genie_resp.text[:300]}")

# COMMAND ----------

# DBTITLE 1,Step 7 - Recommended Glean Test Queries
# MAGIC %md
# MAGIC ## Step 7 — Recommended Test Queries for Glean
# MAGIC
# MAGIC Use these after completing configuration in Glean. All use `samples.tpch` — no setup required.
# MAGIC
# MAGIC ### For Genie (natural language — use in Assistant or Agent)
# MAGIC
# MAGIC | Test | What it validates |
# MAGIC |---|---|
# MAGIC | "How many orders are there?" | Basic count, confirms table access |
# MAGIC | "What are the top 5 countries by total order value?" | Aggregation + sorting |
# MAGIC | "Show me orders with status cancelled" | Filtering on string column |
# MAGIC | "What is the average order value by customer market segment?" | JOIN across tables |
# MAGIC | "Which month had the highest total sales in 1995?" | Date filtering + aggregation |
# MAGIC
# MAGIC ### For SQL action (direct SQL — use in Agent Builder)
# MAGIC
# MAGIC ```sql
# MAGIC -- Basic connectivity test
# MAGIC SELECT COUNT(*) AS total_orders FROM samples.tpch.orders
# MAGIC ```
# MAGIC
# MAGIC ```sql
# MAGIC -- Aggregation test
# MAGIC SELECT o_orderstatus, COUNT(*) AS cnt, ROUND(SUM(o_totalprice), 2) AS total
# MAGIC FROM samples.tpch.orders GROUP BY o_orderstatus ORDER BY total DESC
# MAGIC ```
# MAGIC
# MAGIC ```sql
# MAGIC -- Join test
# MAGIC SELECT c.c_mktsegment, COUNT(*) AS orders, ROUND(AVG(o.o_totalprice), 2) AS avg_value
# MAGIC FROM samples.tpch.orders o
# MAGIC JOIN samples.tpch.customer c ON o.o_custkey = c.c_custkey
# MAGIC GROUP BY c.c_mktsegment ORDER BY orders DESC
# MAGIC ```
